# Generated by Django 5.1 on 2024-08-28 12:00

import django.db.models.deletion
import social_book_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_book_app', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_book_app.customuser'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='', validators=[social_book_app.models.validate_file_extension]),
        ),
    ]
