# Generated by Django 5.1 on 2024-08-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_book_app', '0006_alter_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
